import { DocPage, DocSection, DocBadge, DocH1, DocH2, DocP, DocUl, DocDivider, DocCallout, DocTable } from '../DocComponents'

export default function ManageStrategy() {
  return (
    <DocPage>
      <DocSection>
        <DocBadge color="#22C55E">Traders</DocBadge>
        <DocH1>Managing Your Live Strategy</DocH1>
        <DocP>
          Once your strategy is live, your main job is to monitor performance and notify us if your rules need updating. The agent runs without your involvement — but you need to stay aware of what it's doing.
        </DocP>
      </DocSection>

      <DocDivider />

      <DocSection>
        <DocH2>Your trader dashboard</DocH2>
        <DocUl items={[
          'Live view of all trades placed by your agent',
          'User deposit total (aggregate AUM)',
          'Monthly earnings breakdown (current epoch)',
          'Win rate trailing (30 / 90 / all time)',
          'Current tier badge',
          'Agent status (Active / Paused / Offline)',
        ]} />
      </DocSection>

      <DocDivider />

      <DocSection>
        <DocH2>When to notify us</DocH2>
        <DocUl items={[
          'Your strategy rules change — even a small tweak requires a rebuild',
          'Market conditions change and you want to pause entries on a specific asset',
          'You want to add or remove coins from the agent\'s scan list',
          'You notice the agent taking trades that don\'t match your rules',
          'You want to close a live listing (30-day notice required)',
        ]} />
        <DocCallout type="warning">
          Do NOT attempt to modify the agent behavior yourself. Contact traders@tradelikeme.xyz for any rule change — unauthorized modifications void your listing agreement.
        </DocCallout>
      </DocSection>

      <DocDivider />

      <DocSection>
        <DocH2>Pausing your strategy</DocH2>
        <DocP>
          You can request a pause on new entries at any time. Contact us via Telegram or email. Pauses take effect within 1 hour. Open positions continue to be managed until they close.
        </DocP>
        <DocUl items={[
          'Pause duration: up to 14 days without affecting your listing',
          'Extended pause (14+ days): listing shown as "temporarily paused" to users',
          'Users are notified of pauses via their dashboard and Telegram',
        ]} />
      </DocSection>

      <DocDivider />

      <DocSection>
        <DocH2>Closing your listing</DocH2>
        <DocUl items={[
          '30-day notice required',
          'During notice period: no new users can subscribe, existing users notified',
          'At close: all open positions managed to completion, withdrawals processed',
          'Your strategy data (trade history, win rate) remains on file — you can re-list later',
        ]} />
      </DocSection>

      <DocDivider />

      <DocSection>
        <DocH2>Performance disputes</DocH2>
        <DocP>
          If you believe your tier review is incorrect, you can request a manual verification. We will review the trailing 90-day trade history and recalculate. Disputes must be submitted within 7 days of tier change.
        </DocP>
      </DocSection>

      <DocDivider />

      <DocSection>
        <DocH2>Monthly summary</DocH2>
        <DocP>
          On the 1st of each month, you receive a summary email with:
        </DocP>
        <DocTable
          headers={['Item', 'Detail']}
          rows={[
            ['Epoch P&L', 'Total profit generated by your strategy last month'],
            ['Your earnings', 'Your fee share in USDT'],
            ['User count', 'Number of active subscribers'],
            ['AUM', 'Total assets under management'],
            ['Win rate (epoch)', 'Win rate for the last 30 days'],
            ['Tier confirmation', 'Your current tier for the next 30 days'],
          ]}
        />
      </DocSection>
    </DocPage>
  )
}
